def syn(synonyms: list[str]) -> list[set[str]]:
    return [
        set(syn.split("; "))
        for syn in synonyms
    ]


PROMPTS = syn([
    'individual; person; human',
    'at petrol station; at gas station',
    'biking; bicycling',
    'construction-worker; laborer',
    'two people; pair; two humans',
    'dining; eating',
    'waving; beckoning',
    'group; people; gathering; many humans',
    'on wheelchair; riding wheelchair',
    'looking at phone',
    'playing',
    'pushing shopping cart',
    "pushing stroller",
    'running; jogging',
    'shopping; browsing; buying',
    'sitting on chair or bench',
    'sports; athletics; exercising',
    'standing',
    # 'standing up; standing upright',
    # 'standing up',
    'street-vendor; street-merchant',
    'taking picture; photographing',
    'talking; chatting; speaking',
    'talking on phone; chatting on phone',
    'waiting for bus; waiting at bus station',
    'walking; strolling',
    'with bike; with bicycle',
    'with drink; with beverage',
    'baby; infant; toddler',
    # 'crossing crosswalk; crossing street; crossing road',
    'crossing crosswalk',
    'duplicate; duplicated',
    'elderly; senior',
    'kid; child',
    # 'with cane or walker; walking stick; walking cane',
    'with mobility aids',
    'model_hint',
    'multi-label',
    'no people',
    # 'not sure; confusing; ambiguous',
    'pet; service dog',
    'with pet; with dog',
    'public service; cleaning',
    'riding carriage; riding horse carriage',
    'teenager; teen',
    'working on laptop; working on computer',
    'no interaction',
    'police; law enforcement',
    # 'loading packages; unloading packages',
    'loading packages; unloading packages; loading or unloading packages',
    'reading; reading book',
    'with luggage; with suitcase',
    # 'waiting for food; waiting for drink',
    'waiting for food',
    'taking taxi; taking cab',
    'picnic; picnicking',
    'riding motorcycle; motorcycling',
    'hugging; embracing',
])
